[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
[programs.devnet] ### HW: Added
guitar_contest = "2Hg6qeZGBsMPDDM1RY65Ucwk5JbLrF3D3P9qdYbEfmSU" ### HW: See Program Id in the output of the 1st deployment.

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet" ### HW: Changed from localnet
wallet = "~/Dev/solana-camp.dev/my-solana-wallet/my-keypair.json" ### HW: Updated

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
transfer-mint-authority = "yarn run ts-node scripts/transfer-mint-authority.ts"
backfill-tokens = "yarn run ts-node scripts/backfill-tokens.ts"




